services:
    ollama:
        image: ollama/ollama
        ports:
            - "11434:11434"
        volumes:
            - "./data:/data"  # ready hook
    node:
        image: node:23
        volumes:
            - "./:/app"
        working_dir: /app
        command: pnpm run dev